# Generated by Django 5.0.6 on 2024-07-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_tbl_personal_enquiry_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_personal',
            name='Enquiry_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
