# Generated by Django 5.0.6 on 2024-07-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_tbl_personal_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_personal',
            name='Contact_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tbl_personal',
            name='WhatsApp_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
